<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ApplicationIcon>Assets\FusionCanvasLogo_Square_LightBg.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AvaloniaVirtualDataGrid">
      <HintPath>..\..\lib\AvaloniaVirtualDataGrid\net10.0\AvaloniaVirtualDataGrid.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\FusionCanvasBanner.jpg" />
    <AvaloniaResource Include="Assets\FusionCanvas.ico" />
    <AvaloniaResource Include="Assets\FusionCanvasLogo_Square.png" />
    <AvaloniaResource Include="Assets\FusionCanvasLogo_Square_LightBg.png" />
    <AvaloniaResource Include="Assets\FusionCanvasLogo_Square_LightBg.ico" />
    <AvaloniaResource Include="Assets\Legal\FusionCanvasTermsOfUse.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FusionCanvas.Application\FusionCanvas.Application.csproj" />
    <ProjectReference Include="..\FusionCanvas.Integration\FusionCanvas.Integration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FusionCanvas.App.Tests" />
    <InternalsVisibleTo Include="FusionCanvas.UITests" />
  </ItemGroup>
</Project>
